### PR TITLE
Auto Warp

### PR DESCRIPTION
**Pull request by awWhy**
I think that instant c15 expo, should cost only like 1e10 or 2e10, as its doesnt have any bonus beside just being QoL
(This PR doesnt touch it Price)
Description, Price and etc can be changed for auto Warp.
It works in a way that you cannot warp while its on, but get multiplier to opening cubes based on how many unused warps you have. It will obviously buff a little Quarks gained from opens, that why I made price 5e11 Quarks

### CODE REVIEW

**Comment by krynczak** [comment]
hey @awWhy what happened to your discord account?

**Comment by awWhy** [comment]
Nothing, just dont feel like playing game. I wont be able to resolve conflicts, as I archieved my forks
Will probably close all PR's in a month or two

**Comment by krynczak** [comment]
> Nothing, just dont feel like playing game. I wont be able to resolve conflicts, as I archieved my forks Will probably close all PR's in a month or two

If you feel like coming back, everyone was wondering what happened to you and we're missing talking with you. You contributed a lot to the game and to the discussions.

I hope you change your mind. Anyway, thanks for everything!

**Comment by awWhy** [comment]
Closed. Dont want to wait for eternity, if someone want auto warping can just copy code and picture from here

**Pull request closed without merging**
