### PR TITLE
Bugreports

### PR DESCRIPTION
**Pull request by mustache0110**
Some fixes for reported bugs on discord.

### CODE REVIEW

**Review by KhafraDev — APPROVED** [review]

**Comment by httpsnet** [comment]
Oh, thank you for taking care of some of the issues I caused.
I made a PR without checking you. If either is merged it will cause a conflict.

**Comment by mustache0110** [comment]
The changes in [e314642](https://github.com/Pseudo-Corp/SynergismOfficial/pull/344/commits/e314642cccf8540e9a3d415952780a68d3990bef) and [09cd0e5](https://github.com/Pseudo-Corp/SynergismOfficial/pull/344/commits/09cd0e5e3b7834bdcb81a1a5179b483ee944f746) are identical besides the extra set of parenthesis in your pull, so there is no logic conflict.

**Comment by mustache0110** [comment]
I don't really know where to ask this, but this seems as good of a place as any rather than hijacking a discord channel
@Pseudonian @KhafraDev 
I'm new to git and new to contributing, so bug fixes seem to be an easier place to start. A lot of them are very small fixes, just a few lines. What is the best way to submit them? I created a bug fix branch and committed each fix separately; my assumption being that it makes it easier to review, and easier to drop one fix while being able to merge the rest.

Would you rather them all combined into one commit? Or a PR for each bug? I'm just wondering if too many small commits are a bad thing. Although I expect if you want them all as one commit you can just as easily squash merge? Like I said, I'm just new to git, not really aware of how to fully use it, and want to know if I could be doing it a better way

**Comment by KhafraDev** [comment]
What you did is exactly what I prefer (each bug fix is its own commit).

**Pull request merged**
