### PR TITLE
Fix auto Orbs, add text and some noise fixes

### PR DESCRIPTION
**Pull request by awWhy**
Because too many people complain about it
image
There is also a bug with auto being on OFF after import, but showing itself as ON
(New) from cloudy fix wrong text with using adds; from ab33 move TQE below Singularity one
Also fixed a dot that was hiden away from everyone  image

### CODE REVIEW

**Review by KhafraDev — APPROVED** [review]

**Comment by cloudytheconqueror** [comment]
Previous pull requests related to the add code text fix: #300 #303

**Comment by awWhy** [comment]
OctAsc
Octeract Quarks
I also still have these 2

**Comment by awWhy** [comment]
Removed check for Cookie 3 and Cookie 4 cost on load, because higher in the code there is already better version that does same thing, but for every upgrade (Dont know if it will work properly for more than 1 level, but it works fine for 1 level)

**Comment by awWhy** [comment]
I dont like not being able to squish because of Merge stuff...
Fixed orbs not correctly showing which mode they are after refresh (No idea if in optimal way)

**Pull request merged**
