### PR TITLE
No confirmations mode, open x potions input, update text real life

### PR DESCRIPTION
**Pull request by awWhy**
Some people really wanted this feature (I dont think its of any use though)
New mode for shop confirmation
Open x potions input
Change potions text in real life

Should have no bugs (But everything is possible)

### CODE REVIEW

**Review by KhafraDev — CHANGES_REQUESTED** [review]
.

**Comment by awWhy** [comment]
Dont merge, I found silly silly bug

**Comment by awWhy** [comment]
Closed until I figure out how to make it care that I only want it to work for potions

**Comment by awWhy** [comment]
Merge Instant challenge 2 with new toggle to hide stuff first
Or there will be a lot of conflicts (I will deal with them later)

**Comment by awWhy** [comment]
I might need to close this one, as other duplicate one was merged
Will see sligtly later

**Pull request closed without merging**
