### PR TITLE
Image redo

### PR DESCRIPTION
**Pull request by LucidCrux**
Stuck on a win7 machine so can't use updated node.js. No major code changes though, other than some image path stuff, so hopefully all is fine.

### CODE REVIEW

**Review by KhafraDev — APPROVED** [review]

**Comment by KhafraDev** [comment]
there are some merge conflicts

**Comment by LucidCrux** [comment]
Looks like a couple easy fixes for a few files added since I started work. You want me to resolve them, or you have whoever merges handle it?

**Comment by awWhy** [comment]
I wonder if with image changes this big would had been to create alternative theme, so people could choose, but whatever.
image
Looks like some images still missing

**Comment by httpsnet** [comment]
I don't think the black in these images is a correct representation.
Pictures/CubeUpgrade67.png Pictures/SingularityCookies4.png Pictures/SingularityAscensions.png Pictures/SingularityCubes1.png

the following csslint error

**Comment by LucidCrux** [comment]
Black on cookies was intended as it looked weird to me on other themes without it, but if people prefer otherwise, it's an easy change.

**Comment by Pseudonian** [comment]
With the game almost done, I don't anticipate adding many more sprites- that means that I am more interested in moving forward with this PR.

**Comment by LucidCrux** [comment]
Okay, I've been gone a while, I will mess with this some more in a bit. Also got a win 11 machine, so might be able to do a proper test before submitting.

**Comment by LucidCrux** [comment]
I've gone ahead and added an icon set toggle now. The code style isn't exactly like the other toggles, and this is my first time messing with complex typescript instead of just js, but seems to work fine. If anything looks funky, let me know.

**Comment by awWhy** [comment]
Khafra will probably ask instead of 'Pictures/' + player.iconSet + '/Diamond.png' to do `Pictures/${player.iconSet}/Diamond.png`;
Also 
let changeTo = 'Default';
    switch (current) {
        case 'Default':
            changeTo = 'Legacy';
            break;
        case 'Legacy' :
            changeTo = 'Default';
            break;
        default:
            changeTo = 'Default';
            break;
    }
    
    can be done as:
    const changeTo = current === 'Default' ? 'Legacy' : 'Default'
    
    Or you can remove case 'Legacy' and default since changeTo starts as them; (Or then changeTo: String; Without =)

**Comment by KhafraDev** [comment]
Thanks for maintaining this pr for so long!

**Comment by LucidCrux** [comment]
Okay, should be good to merge again. I did add a image fallback, so all you have to do is put new images in the legacy folder and it will still work for all other icon sets. Didn't do a popup set selector like just added for themes, but it should be more compatible for doing one of those if desired also.

**Comment by Pseudonian** [comment]
I'm currently testing this in local. If all things are good I will merge this tomorrow. Thank you so much for maintaining this wonderful PR for as long as you have! Extremely high-quality images and overall great aesthetic.

Cheers 🥂

**Comment by LucidCrux** [comment]
Yeah, no problem. I'll try to check in every once in a while to see if new images are needed.

**Pull request merged**
